// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from './routes/Client.tsx'
import * as $1 from './routes/Query.tsx'
import * as $2 from './routes/Server.tsx'
import * as $3 from './routes/_app.tsx'
import * as $4 from './routes/api/[trpc].ts'
import * as $5 from './routes/index.tsx'
import * as $$0 from './islands/ClientSide.tsx'
import * as $$1 from './islands/Provider.tsx'
import * as $$2 from './islands/Query.tsx'

const manifest = {
  routes: {
    './routes/Client.tsx': $0,
    './routes/Query.tsx': $1,
    './routes/Server.tsx': $2,
    './routes/_app.tsx': $3,
    './routes/api/[trpc].ts': $4,
    './routes/index.tsx': $5,
  },
  islands: {
    './islands/ClientSide.tsx': $$0,
    './islands/Provider.tsx': $$1,
    './islands/Query.tsx': $$2,
  },
  baseUrl: import.meta.url,
}

export default manifest
