// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from './routes/_app.tsx'
import * as $1 from './routes/api/[trpc].ts'
import * as $2 from './routes/api/oauth.ts'
import * as $3 from './routes/client.tsx'
import * as $4 from './routes/index.tsx'
import * as $5 from './routes/query.tsx'
import * as $6 from './routes/server.tsx'
import * as $7 from './routes/signin.ts'
import * as $8 from './routes/signout.tsx'
import * as $$0 from './islands/ClientSide.tsx'
import * as $$1 from './islands/Provider.tsx'
import * as $$2 from './islands/Query.tsx'

const manifest = {
  routes: {
    './routes/_app.tsx': $0,
    './routes/api/[trpc].ts': $1,
    './routes/api/oauth.ts': $2,
    './routes/client.tsx': $3,
    './routes/index.tsx': $4,
    './routes/query.tsx': $5,
    './routes/server.tsx': $6,
    './routes/signin.ts': $7,
    './routes/signout.tsx': $8,
  },
  islands: {
    './islands/ClientSide.tsx': $$0,
    './islands/Provider.tsx': $$1,
    './islands/Query.tsx': $$2,
  },
  baseUrl: import.meta.url,
}

export default manifest
